version: "3"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile-circleci
    environment:
      - POSTGRES_DSN=host=db port=5432 user=$POSTGRES_USER password=$POSTGRES_PASSWORD dbname=$POSTGRES_DB sslmode=disable
      - GO111MODULE=on
    ports:
      - 8080:80
    tty: true
  
  db:
    image: postgres:11
    environment:
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_DB: $POSTGRES_DB
      POSTGRES_INITDB_ARGS: --encoding=UTF-8
      TZ: "Asia/Tokyo"
    restart: always
    volumes:
      - dbdata:/var/lib/postgresql/data

volumes:
  dbdata:
