version: "3"
services:
  app:
    image: tsuzu/coding_challenge_03
    environment:
      - POSTGRES_DSN=host=db port=5432 user=$POSTGRES_USER password=$POSTGRES_PASSWORD dbname=$POSTGRES_DB sslmode=disable
    ports:
      - 8080:80
    command: /bin/dockerize -wait tcp://db:5432 /bin/api_server --migrate
  
  db:
    image: postgres:11
    environment:
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_DB: $POSTGRES_DB
      POSTGRES_INITDB_ARGS: --encoding=UTF-8
    restart: always
    volumes:
      - dbdata:/var/lib/postgresql/data

volumes:
  dbdata:
